// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knuovrhhirpzefjgempb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudW92cmhoaXJwemVmamdlbXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Njc5NDEsImV4cCI6MjA2NDM0Mzk0MX0.ZxX3zY5sSH8ouElquzwj5CRYJ_4jZ4OSDMlLfM5Jkbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);